complexity:
  active: true
  LongMethod:
    threshold: 20
  LongParameterList:
    threshold: 5
  LargeClass:
    threshold: 150
  ComplexMethod:
    threshold: 10
  TooManyFunctions:
    threshold: 10
  ComplexCondition:
    threshold: 3

style:
  active: true
  WildcardImport:
    active: false
  ModifierOrder:
    active: true
  PackageNaming:
    active: true
    packagePattern: '^[a-z]+(\.[a-z][a-z0-9]*)*$'
  ClassNaming:
    active: true
    classPattern: '[A-Z$][a-zA-Z$]*'
  EnumNaming:
    active: true
    enumEntryPattern: '^[A-Z$][a-zA-Z_$]*$'
  FunctionNaming :
    active: true
    functionPattern: '^[a-z$][a-zA-Z$0-9]*$'
  FunctionMaxLength:
    active: false
    maximumFunctionNameLength: 25
  FunctionMinLength:
    active: false
    minimumFunctionNameLength: 3
  VariableNaming :
    active: true
    variablePattern: '^(_)?[a-z$][a-zA-Z$0-9]*$'
  ConstantNaming :
    active: true
    constantPattern: '^([A-Z_]*|serialVersionUID)$'
  VariableMaxLength:
    active: false
    maximumVariableNameLength: 17
  VariableMinLength:
    active: false
    minimumVariableNameLength: 3
  MaxLineLength:
    active: true
    maxLineLength: 150
    excludePackageStatements: false
    excludeImportStatements: false
  UnnecessaryParentheses:
    active: false
  ForbiddenComment:
    active: false

comments:
  active: true
  CommentOverPrivateMethod:
    active: false
  CommentOverPrivateProperty:
    active: false
  NoDocOverPublicClass:
    active: true
  NoDocOverPublicMethod:
    active: false
  UndocumentedPublicFunction:
    active: false

potential-bugs:
  active: true
  DuplicateCaseInWhenExpression:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  LateinitUsage:
    active: false

performance:
  active: true
  ForEachOnRange:
    active: true

exceptions:
  active: true

empty-blocks:
  active: true
